
language: node_js
cache:
  directories:
  - "$HOME/.npm"
notifications:
  email: false
node_js:
- '10'
script:
- npm run lint
after_success:
- npm run release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
